### ISSUE TITLE
Clarification on Code Relevance to Adv-KD Paper

### ISSUE THREAD

**Issue by One1209** [kidist-amde/Adv-KD#3]
I hope this message finds you well. I recently came across the code you provided on GitHub at [this link](https://github.com/kidist-amde/Adv-KD/tree/main) and noticed that it appears to implement a diffusion model for image generation. However, I am wondering if this code is actually related to your paper "Adv-KD: Adversarial Knowledge Distillation for Faster Diffusion Sampling."

Could you please clarify whether the code uploaded on GitHub is indeed linked to the Adv-KD paper, or if there was an error in the upload? I would greatly appreciate any clarification you could provide.

Thank you for your time and assistance.

**Comment by kidist-amde** [comment]
Hello,

Thank you for pointing this out. It seems there is indeed an issue with the repository.
 The code you found is linked to the wrong repository and is not associated with the "Adv-KD" paper.
My apologies for the mix-up. I'll correct the link and ensure the proper code is available soon.

Best regards,
Kidist

**Comment by One1209** [comment]
When can I upload the relevant code，thanks!

**Comment by kidist-amde** [comment]
You should now find the correct code. Thank you!
